name: .NET Core

on:
  push:
    branches: [ master, acceptence ]
  pull_request:
    branches: [ master, acceptence ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{ secrets.SOLUTION_PATH }}
    - name: Build
      run: dotnet build ${{ secrets.SOLUTION_PATH }} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ secrets.SOLUTION_PATH }} --no-restore --verbosity normal
